# - - - - - - - - - - - - - - - - - - - - - -
# → JakesRTP Config!  Have fun configuring! ←
# - - - - - - - - - - - - - - - - - - - - - -
# Old configs may not run correctly.
# Please don't edit config-version.
config-version: 1.5
# Should the plugin try and load an old config? Whenever a change is made to the structure of the config, the
#   version is increased. On startup, the plugin compares the version of the existing config to the version
#   that it is expecting, and will either (a) attempt to load the older version of the config regardless of
#   if the versions match, or (b) back up the existing config, and load the new one in its place.
# If this is set to true, there is a large chance that the plugin will crash on load, BUT that may actually be
#   the preferred course of action as it makes it very apparent that the config needs to be updated. Then it
#   can be temporarily set to false so that the plugin can load in the new config, and all the old values that
#   still apply can be copied over.
run-old-configs: false
# ↑ IMPORTANT SETTING ↑
random-teleport-settings default: # The word 'default' here is the name of this config section
  enabled: true   # Should we load this config?
  enabled-worlds: # Nether and End worlds are not currently supported, so please don't list them here
    - world
    - yer  # You can remove this one, its here as an example
  shape:
    allowed-values:
      a: 'Square (radius & center)'
      b: 'Circle (radius & center)'
    value: a
  defining-points:
    radius-center:
      radius:
        max: 2000
        min: 1000
      center:
        allowed-values:
          a: "World spawn"
          b: "Player's current location"
          c: "The x and z as set in config"
        value: a
        x: 0
        z: 0
  cooldown:      # Cooldown between uses. Can be bypassed with permission node jakesrtp.nocooldown
    seconds: 30  # Default: 30
  ############## # Everything past this point in the config probably does not need to get changed
  low-bound:     # The lowest point a player can be RTP'd to.
    value: 48    # Default: 48
  check-radius:  # How many blocks away from the initial spot to check.
    x-z: 2       # Default: 2    | Max spots to check per attempt is equal to:
    vert: 2      # Default: 2    | (2*vert+1)*(2*(x-z)+1)^2
  max-attempts:  # If the random location, and all (by default 125) close spots are found to be unsafe,
    value: 5     # how many attempts can we make? Minimum: 1; Default: 5

# You can keep copying and pasting these for more configs, just change the word(s) at the end
random-teleport-settings example:
  enabled: false
  enabled-worlds:
    - world_the_end
  shape:
    value: b
  defining-points:
    radius-center:
      radius:
        max: 5000
        min: 3000
      center:
        value: c
        x: 1000000
        z: 1000000
  cooldown:
    seconds: 4000
  low-bound:
    value: 48
  check-radius:
    x-z: 2
    vert: 2
  max-attempts:
    value: 8
